#ifndef MACHINERY_GLOBAL_H
#define MACHINERY_GLOBAL_H

#include <QtGlobal>

#if defined(MACHINERY_LIBRARY)
#define MACHINERYSHARED_EXPORT Q_DECL_EXPORT
#else
#define MACHINERYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MACHINERY_GLOBAL_H
